### ISSUE TITLE
请问本地日志已经输出 query ok ，但是数据库却没有存入成功，这可能是什么原因？

### ISSUE THREAD

**Issue by hypergraphdev** [songtianyi/tdengine-rust-bindings#1]
您好！我这边遇到一个比较奇怪的情况。就是部分查询发现客户端已经得到了
println!("query '{}' ok", s); 
日志的输出，但是服务器端数据却未被插入，请问这有可能是哪个环节出了问题

这个现象没有所有表格重现，但是在一个数据量比较大的数据表上非常明显。

**Comment by songtianyi** [comment]
数据库查不到，但是接口可以查到数据？
